name: Générer les questions du jour

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter le script de génération
        run: node scripts/generateDailyQuestions.js

      - name: Construire le projet
        run: npm run build

      - name: Remplacer le contenu de docs avec dist
        run: |
          rm -rf docs
          cp -r dist docs

      - name: Commit & push des fichiers mis à jour
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs public/data/dailyQuestions.json
          git commit -m "MàJ daily questions et build 📅"
          git push
