name: Générer les questions du jour

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install
      
      - name: Rendre Vite exécutable
        run: chmod +x node_modules/.bin/vite

      - name: Exécuter le script de génération
        run: node scripts/generateDailyQuestions.js

      - name: Construire le projet avec Vite via npx
        run: npx vite build

      - name: Commit & push du JSON et du build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/dailyQuestions.json docs
          git commit -m "MàJ daily questions 📅"
          git push
